[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easy_decorate_output"
version = "0.4.0"
authors = [
  { name = "Don221128" }
]
description = "一個用於自訂美化終端機輸出的輕量級工具庫"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich>=15.0.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["easy_decorate_output*"]